# Generated by Django 5.2.17 on 2026-09-02 18:47

import apps.grievances.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Grievance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_id",
                    models.CharField(
                        default=apps.grievances.models.generate_tracking_id,
                        editable=False,
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("passenger_name", models.CharField(max_length=120)),
                ("passenger_phone", models.CharField(max_length=15)),
                (
                    "pnr_number",
                    models.CharField(
                        blank=True,
                        help_text="10-digit Indian Railways PNR",
                        max_length=10,
                    ),
                ),
                ("train_number", models.CharField(blank=True, max_length=10)),
                (
                    "coach_number",
                    models.CharField(
                        blank=True, help_text="e.g. B3, S6", max_length=10
                    ),
                ),
                (
                    "seat_number",
                    models.CharField(blank=True, help_text="e.g. 42", max_length=10),
                ),
                (
                    "current_station",
                    models.CharField(
                        blank=True,
                        help_text="Nearest station or train location",
                        max_length=100,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SECURITY", "Security / RPF Assistance"),
                            ("MEDICAL", "Medical Emergency"),
                            ("CLEANLINESS", "Cleanliness & Sanitation (Coach Mitra)"),
                            ("ELECTRICAL", "Electrical & Air Conditioning"),
                            ("CATERING", "Food & Catering Services"),
                            ("STAFF_BEHAVIOR", "Staff / TTE Conduct"),
                            ("DELAY_INFRA", "Train Delay & Infrastructure"),
                            ("GENERAL", "General Inquiry & Miscellaneous"),
                        ],
                        default="GENERAL",
                        max_length=30,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "🔴 Critical (Emergency / Safety)"),
                            ("HIGH", "🟠 High (Major Comfort / Sanitation)"),
                            ("MEDIUM", "🟡 Medium (Standard Maintenance)"),
                            ("LOW", "🟢 Low (Minor / General)"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open / Registered"),
                            ("IN_PROGRESS", "In Progress / Assigned"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed / Verified"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "urgency_score",
                    models.PositiveIntegerField(
                        default=50, help_text="AI calculated urgency 0-100"
                    ),
                ),
                (
                    "sentiment_label",
                    models.CharField(default="Negative", max_length=50),
                ),
                ("is_ai_escalated", models.BooleanField(default=False)),
                (
                    "assigned_department",
                    models.CharField(
                        blank=True,
                        default="On-Board Housekeeping / OBHS",
                        max_length=100,
                    ),
                ),
                (
                    "attachment",
                    models.ImageField(
                        blank=True, null=True, upload_to="grievance_attachments/"
                    ),
                ),
                ("resolution_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_grievances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "passenger",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lodged_grievances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GrievanceAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_status", models.CharField(max_length=30)),
                ("new_status", models.CharField(max_length=30)),
                ("remarks", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "grievance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="grievances.grievance",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="GrievanceComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_name", models.CharField(blank=True, max_length=100)),
                ("message", models.TextField()),
                ("is_official_update", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grievance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="grievances.grievance",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
