# Generated by Django 5.2.17 on 2026-09-02 18:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("zone", models.CharField(default="NR", max_length=50)),
                ("division", models.CharField(default="Delhi", max_length=50)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("number_of_platforms", models.PositiveIntegerField(default=5)),
                ("has_wifi", models.BooleanField(default=True)),
                ("has_medical_booth", models.BooleanField(default=True)),
                (
                    "rpf_post_phone",
                    models.CharField(default="182 / 139", max_length=20),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Train",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("train_number", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "train_type",
                    models.CharField(
                        choices=[
                            ("VANDE_BHARAT", "Vande Bharat Express"),
                            ("RAJDHANI", "Rajdhani Express"),
                            ("SHATABDI", "Shatabdi Express"),
                            ("SUPERFAST", "Superfast Express"),
                            ("EXPRESS", "Express / Mail"),
                            ("LOCAL", "Suburban / Local"),
                            ("FREIGHT", "Freight Train"),
                        ],
                        default="SUPERFAST",
                        max_length=30,
                    ),
                ),
                (
                    "runs_on",
                    models.CharField(
                        default="Daily",
                        help_text="e.g. Daily or Mon, Wed, Fri",
                        max_length=50,
                    ),
                ),
                ("total_coaches", models.PositiveIntegerField(default=18)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ON_TIME", "On Time"),
                            ("DELAYED", "Delayed"),
                            ("CANCELLED", "Cancelled"),
                            ("DIVERTED", "Diverted"),
                            ("ARRIVED", "Arrived"),
                            ("RUNNING", "Running Live"),
                        ],
                        default="ON_TIME",
                        max_length=20,
                    ),
                ),
                (
                    "delay_minutes",
                    models.IntegerField(
                        default=0, help_text="Delay in minutes (0 means on time)"
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "current_station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trains_currently_here",
                        to="trains.station",
                    ),
                ),
                (
                    "destination_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arriving_trains",
                        to="trains.station",
                    ),
                ),
                (
                    "next_station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trains_approaching",
                        to="trains.station",
                    ),
                ),
                (
                    "source_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departing_trains",
                        to="trains.station",
                    ),
                ),
            ],
            options={
                "ordering": ["train_number"],
            },
        ),
        migrations.CreateModel(
            name="PlatformAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform_number", models.PositiveIntegerField()),
                ("expected_arrival", models.DateTimeField()),
                ("expected_departure", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Approaching", "Approaching"),
                            ("Docked", "Docked / Boarding"),
                            ("Departed", "Departed"),
                            ("Delayed", "Delayed"),
                        ],
                        default="Approaching",
                        max_length=30,
                    ),
                ),
                (
                    "assigned_by",
                    models.CharField(default="AI Automated Dispatch", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_allocations",
                        to="trains.station",
                    ),
                ),
                (
                    "train",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="trains.train"
                    ),
                ),
            ],
            options={
                "ordering": ["expected_arrival"],
            },
        ),
        migrations.CreateModel(
            name="CoachComposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coach_number",
                    models.CharField(help_text="e.g. C1, B2, S4, DL1", max_length=10),
                ),
                (
                    "coach_type",
                    models.CharField(
                        default="Sleeper",
                        help_text="e.g. AC 3 Tier, Executive Chair, General",
                        max_length=50,
                    ),
                ),
                ("capacity", models.PositiveIntegerField(default=72)),
                ("current_occupancy", models.PositiveIntegerField(default=50)),
                (
                    "crowd_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low (< 40%)"),
                            ("MODERATE", "Moderate (40-75%)"),
                            ("HIGH", "High (75-95%)"),
                            ("OVERCROWDED", "Overcrowded (> 95%)"),
                        ],
                        default="MODERATE",
                        max_length=20,
                    ),
                ),
                ("ac_working", models.BooleanField(default=True)),
                (
                    "cleanliness_score",
                    models.FloatField(
                        default=4.5,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "train",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coaches",
                        to="trains.train",
                    ),
                ),
            ],
            options={
                "ordering": ["train", "coach_number"],
            },
        ),
        migrations.CreateModel(
            name="TrainSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stop_number", models.PositiveIntegerField()),
                ("arrival_time", models.TimeField(blank=True, null=True)),
                ("departure_time", models.TimeField(blank=True, null=True)),
                ("halt_minutes", models.PositiveIntegerField(default=2)),
                ("distance_km", models.PositiveIntegerField(default=0)),
                ("day_number", models.PositiveIntegerField(default=1)),
                ("platform_number", models.PositiveIntegerField(default=1)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_trains",
                        to="trains.station",
                    ),
                ),
                (
                    "train",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="trains.train",
                    ),
                ),
            ],
            options={
                "ordering": ["train", "stop_number"],
                "unique_together": {("train", "stop_number")},
            },
        ),
    ]
