# Generated by Django 5.2.17 on 2026-09-08 19:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('zone', models.CharField(default='NR', max_length=50)),
                ('division', models.CharField(default='Delhi', max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('km_from_source', models.DecimalField(decimal_places=3, default=0.0, max_digits=8)),
                ('number_of_platforms', models.PositiveIntegerField(default=5)),
                ('has_wifi', models.BooleanField(default=True)),
                ('has_medical_booth', models.BooleanField(default=True)),
                ('rpf_post_phone', models.CharField(default='182 / 139', max_length=20)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('train_number', models.CharField(db_index=True, max_length=10, unique=True)),
                ('train_name', models.CharField(max_length=150)),
                ('train_type', models.CharField(choices=[('PRESTIGE_SUPERFAST', 'Prestige Superfast (Rajdhani / Shatabdi / Vande Bharat)'), ('PASSENGER_EXPRESS', 'Passenger Express / Mail'), ('SUBURBAN_EMU', 'Suburban EMU / Local'), ('CONTAINER_FREIGHT', 'Container Freight (CONCOR / DFC)'), ('BULK_FREIGHT', 'Bulk Freight (Coal / Minerals / BOXN)')], db_index=True, default='PASSENGER_EXPRESS', max_length=30)),
                ('priority_rank', models.PositiveIntegerField(db_index=True, default=100, help_text='Lower number indicates higher traffic priority (e.g. Rajdhani=1, Shatabdi=2, Freight=50)')),
                ('source_station', models.CharField(default='NDLS', max_length=10)),
                ('destination_station', models.CharField(default='CNB', max_length=10)),
                ('is_daily', models.BooleanField(default=True)),
                ('operating_days_mask', models.CharField(default='1111111', help_text='7-digit binary mask for Mon-Sun (1=Runs, 0=Does not run)', max_length=7)),
                ('traction_type', models.CharField(choices=[('ELECTRIC', 'Electric (25kV AC OHE)'), ('DIESEL', 'Diesel'), ('DUAL', 'Dual Mode / Hybrid')], default='ELECTRIC', max_length=20)),
                ('max_speed_kmh', models.PositiveIntegerField(default=130)),
                ('length_meters', models.DecimalField(decimal_places=2, default=650.0, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority_rank', 'train_number'],
                'indexes': [models.Index(fields=['train_type', 'priority_rank'], name='idx_trn_type_priority')],
            },
        ),
        migrations.CreateModel(
            name='PlatformAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_number', models.PositiveIntegerField()),
                ('expected_arrival', models.DateTimeField()),
                ('expected_departure', models.DateTimeField()),
                ('status', models.CharField(default='Approaching', max_length=30)),
                ('assigned_by', models.CharField(default='AI Automated Dispatch', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_allocations', to='trains.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.train')),
            ],
            options={
                'ordering': ['expected_arrival'],
            },
        ),
        migrations.CreateModel(
            name='CoachComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_number', models.CharField(max_length=10)),
                ('coach_type', models.CharField(default='Sleeper', max_length=50)),
                ('capacity', models.PositiveIntegerField(default=72)),
                ('current_occupancy', models.PositiveIntegerField(default=50)),
                ('ac_working', models.BooleanField(default=True)),
                ('cleanliness_score', models.FloatField(default=4.5, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='trains.train')),
            ],
            options={
                'ordering': ['train', 'coach_number'],
            },
        ),
        migrations.CreateModel(
            name='TrainLiveStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('journey_date', models.DateField(db_index=True)),
                ('current_station_code', models.CharField(db_index=True, max_length=10)),
                ('current_km', models.DecimalField(decimal_places=3, default=0.0, max_digits=8)),
                ('delay_minutes', models.IntegerField(default=0, help_text='Negative means early, 0 means on time, >0 means delayed')),
                ('speed_kmh', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('ON_TIME', 'On Time'), ('RUNNING', 'Running'), ('DELAYED', 'Delayed'), ('DIVERTED', 'Diverted'), ('REGULATED', 'Regulated'), ('CANCELLED', 'Cancelled'), ('ARRIVED', 'Arrived')], default='RUNNING', max_length=20)),
                ('active_caution_orders', models.JSONField(blank=True, default=list)),
                ('last_reported_at', models.DateTimeField(auto_now=True)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_status_records', to='trains.train')),
            ],
            options={
                'ordering': ['-journey_date', 'delay_minutes'],
                'indexes': [models.Index(fields=['current_station_code', 'delay_minutes'], name='idx_live_stn_delay')],
                'unique_together': {('train', 'journey_date')},
            },
        ),
        migrations.CreateModel(
            name='TrainSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('station_code', models.CharField(db_index=True, max_length=10)),
                ('station_sequence', models.PositiveIntegerField()),
                ('scheduled_arrival_time', models.TimeField(blank=True, null=True)),
                ('scheduled_departure_time', models.TimeField()),
                ('platform_number', models.CharField(blank=True, max_length=5, null=True)),
                ('corridor_section_id', models.CharField(blank=True, max_length=36, null=True)),
                ('km_milestone', models.DecimalField(decimal_places=3, default=0.0, max_digits=8)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='trains.train')),
            ],
            options={
                'ordering': ['train', 'station_sequence'],
                'indexes': [models.Index(fields=['station_code'], name='idx_schedules_station')],
                'unique_together': {('train', 'station_sequence')},
            },
        ),
    ]
