# Generated by Django 5.2.17 on 2026-09-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='direction',
            field=models.CharField(choices=[('UP', 'UP Line (Towards NDLS)'), ('DOWN', 'DOWN Line (Towards CNB)')], db_index=True, default='DOWN', max_length=10),
        ),
        migrations.AddField(
            model_name='train',
            name='pax_capacity',
            field=models.PositiveIntegerField(default=1200, help_text='Passenger capacity for delay impact scoring'),
        ),
        migrations.AddField(
            model_name='trainlivestatus',
            name='current_section',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='trainlivestatus',
            name='heading',
            field=models.FloatField(default=90.0, help_text='Direction angle in degrees (0=North, 90=East, etc.)'),
        ),
        migrations.AddField(
            model_name='trainlivestatus',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainlivestatus',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
