# Generated by Django 5.2.17 on 2026-09-06 20:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trains", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainLiveStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("journey_date", models.DateField(db_index=True)),
                (
                    "current_station_code",
                    models.CharField(db_index=True, max_length=10),
                ),
                (
                    "current_km",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
                ),
                (
                    "delay_minutes",
                    models.IntegerField(
                        default=0,
                        help_text="Negative means early, 0 means on time, >0 means delayed",
                    ),
                ),
                (
                    "speed_kmh",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ON_TIME", "On Time"),
                            ("RUNNING", "Running"),
                            ("DELAYED", "Delayed"),
                            ("DIVERTED", "Diverted"),
                            ("REGULATED", "Regulated"),
                            ("CANCELLED", "Cancelled"),
                            ("ARRIVED", "Arrived"),
                        ],
                        default="RUNNING",
                        max_length=20,
                    ),
                ),
                ("active_caution_orders", models.JSONField(blank=True, default=list)),
                ("last_reported_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-journey_date", "delay_minutes"],
            },
        ),
        migrations.AlterModelOptions(
            name="train",
            options={"ordering": ["priority_rank", "train_number"]},
        ),
        migrations.AlterModelOptions(
            name="trainschedule",
            options={"ordering": ["train", "station_sequence"]},
        ),
        migrations.RenameField(
            model_name="train",
            old_name="name",
            new_name="train_name",
        ),
        migrations.RenameField(
            model_name="train",
            old_name="last_updated",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="trainschedule",
            old_name="arrival_time",
            new_name="scheduled_arrival_time",
        ),
        migrations.RenameField(
            model_name="trainschedule",
            old_name="stop_number",
            new_name="station_sequence",
        ),
        migrations.RemoveField(
            model_name="coachcomposition",
            name="crowd_level",
        ),
        migrations.RemoveField(
            model_name="train",
            name="current_station",
        ),
        migrations.RemoveField(
            model_name="train",
            name="delay_minutes",
        ),
        migrations.RemoveField(
            model_name="train",
            name="next_station",
        ),
        migrations.RemoveField(
            model_name="train",
            name="runs_on",
        ),
        migrations.RemoveField(
            model_name="train",
            name="status",
        ),
        migrations.RemoveField(
            model_name="train",
            name="total_coaches",
        ),
        migrations.AlterUniqueTogether(
            name="trainschedule",
            unique_together={("train", "station_sequence")},
        ),
        migrations.AddField(
            model_name="station",
            name="km_from_source",
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name="train",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="train",
            name="is_daily",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="train",
            name="length_meters",
            field=models.DecimalField(decimal_places=2, default=650.0, max_digits=7),
        ),
        migrations.AddField(
            model_name="train",
            name="max_speed_kmh",
            field=models.PositiveIntegerField(default=130),
        ),
        migrations.AddField(
            model_name="train",
            name="operating_days_mask",
            field=models.CharField(
                default="1111111",
                help_text="7-digit binary mask for Mon-Sun (1=Runs, 0=Does not run)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="train",
            name="priority_rank",
            field=models.PositiveIntegerField(
                db_index=True,
                default=100,
                help_text="Lower number indicates higher traffic priority (e.g. Rajdhani=1, Shatabdi=2, Freight=50)",
            ),
        ),
        migrations.AddField(
            model_name="train",
            name="traction_type",
            field=models.CharField(
                choices=[
                    ("ELECTRIC", "Electric (25kV AC OHE)"),
                    ("DIESEL", "Diesel"),
                    ("DUAL", "Dual Mode / Hybrid"),
                ],
                default="ELECTRIC",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="trainschedule",
            name="corridor_section_id",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name="trainschedule",
            name="km_milestone",
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name="trainschedule",
            name="scheduled_departure_time",
            field=models.TimeField(default="06:00:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trainschedule",
            name="station_code",
            field=models.CharField(db_index=True, default="NDLS", max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="coachcomposition",
            name="coach_number",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="coachcomposition",
            name="coach_type",
            field=models.CharField(default="Sleeper", max_length=50),
        ),
        migrations.AlterField(
            model_name="platformallocation",
            name="status",
            field=models.CharField(default="Approaching", max_length=30),
        ),
        migrations.AlterField(
            model_name="station",
            name="code",
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="train",
            name="destination_station",
            field=models.CharField(default="CNB", max_length=10),
        ),
        migrations.AlterField(
            model_name="train",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="train",
            name="source_station",
            field=models.CharField(default="NDLS", max_length=10),
        ),
        migrations.AlterField(
            model_name="train",
            name="train_number",
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="train",
            name="train_type",
            field=models.CharField(
                choices=[
                    (
                        "PRESTIGE_SUPERFAST",
                        "Prestige Superfast (Rajdhani / Shatabdi / Vande Bharat)",
                    ),
                    ("PASSENGER_EXPRESS", "Passenger Express / Mail"),
                    ("SUBURBAN_EMU", "Suburban EMU / Local"),
                    ("CONTAINER_FREIGHT", "Container Freight (CONCOR / DFC)"),
                    ("BULK_FREIGHT", "Bulk Freight (Coal / Minerals / BOXN)"),
                ],
                db_index=True,
                default="PASSENGER_EXPRESS",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="trainschedule",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="trainschedule",
            name="platform_number",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddIndex(
            model_name="train",
            index=models.Index(
                fields=["train_type", "priority_rank"], name="idx_trn_type_priority"
            ),
        ),
        migrations.AddIndex(
            model_name="trainschedule",
            index=models.Index(fields=["station_code"], name="idx_schedules_station"),
        ),
        migrations.AddField(
            model_name="trainlivestatus",
            name="train",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="live_status_records",
                to="trains.train",
            ),
        ),
        migrations.RemoveField(
            model_name="trainschedule",
            name="day_number",
        ),
        migrations.RemoveField(
            model_name="trainschedule",
            name="departure_time",
        ),
        migrations.RemoveField(
            model_name="trainschedule",
            name="distance_km",
        ),
        migrations.RemoveField(
            model_name="trainschedule",
            name="halt_minutes",
        ),
        migrations.RemoveField(
            model_name="trainschedule",
            name="station",
        ),
        migrations.AddIndex(
            model_name="trainlivestatus",
            index=models.Index(
                fields=["current_station_code", "delay_minutes"],
                name="idx_live_stn_delay",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trainlivestatus",
            unique_together={("train", "journey_date")},
        ),
    ]
