# Generated by Django 5.2.17 on 2026-09-02 18:47

import apps.emergency.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyHelpline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("number", models.CharField(max_length=50)),
                ("category", models.CharField(default="Railways", max_length=50)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("is_toll_free", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="RPFUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_name", models.CharField(max_length=120)),
                ("badge_officer", models.CharField(max_length=100)),
                ("station_base", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Available", "Available / On Patrol"),
                            ("Dispatched", "Dispatched on Incident"),
                            ("Off_Duty", "Off Duty"),
                        ],
                        default="Available",
                        max_length=20,
                    ),
                ),
                ("latitude", models.FloatField(default=28.6139)),
                ("longitude", models.FloatField(default=77.209)),
            ],
            options={
                "ordering": ["unit_name"],
            },
        ),
        migrations.CreateModel(
            name="SOSAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_id",
                    models.CharField(
                        default=apps.emergency.models.generate_sos_id,
                        editable=False,
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("passenger_name", models.CharField(max_length=120)),
                ("passenger_phone", models.CharField(max_length=15)),
                (
                    "emergency_type",
                    models.CharField(
                        choices=[
                            ("SECURITY", "🚨 Security Threat / Violence / Assault"),
                            ("MEDICAL", "🚑 Critical Medical Emergency"),
                            ("FIRE_SMOKE", "🔥 Fire / Smoke / Short Circuit"),
                            ("HARASSMENT", "⚠️ Women Safety / Harassment"),
                            ("SUSPICIOUS_OBJECT", "💣 Unattended / Suspicious Object"),
                            ("COACH_DISASTER", "💥 Derailment / Train Incident"),
                        ],
                        default="SECURITY",
                        max_length=30,
                    ),
                ),
                ("train_number", models.CharField(blank=True, max_length=20)),
                ("coach_number", models.CharField(blank=True, max_length=10)),
                ("seat_number", models.CharField(blank=True, max_length=10)),
                (
                    "current_location_desc",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Between Allahabad & Pt. Deen Dayal Upadhyaya Jn",
                        max_length=200,
                    ),
                ),
                ("latitude", models.FloatField(default=28.6139)),
                ("longitude", models.FloatField(default=77.209)),
                ("details", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "🔴 Active / Blinking Beacon"),
                            ("RESPONDING", "🟡 RPF Dispatched / En Route"),
                            ("RESOLVED", "🟢 Neutralized & Safe"),
                            ("FALSE_ALARM", "⚪ False Alarm"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "rpf_unit_dispatched",
                    models.CharField(
                        blank=True,
                        default="RPF Quick Reaction Team (QRT)",
                        max_length=150,
                    ),
                ),
                ("response_notes", models.TextField(blank=True)),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_sos_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "passenger",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_sos_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-triggered_at"],
            },
        ),
    ]
