# Generated by Django 5.2.17 on 2026-09-02 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PASSENGER", "Passenger"),
                            ("STATION_MASTER", "Station Master"),
                            ("RPF_OFFICER", "RPF Security Officer"),
                            ("MAINTENANCE_TECH", "Maintenance Engineer"),
                            ("ADMIN", "Railway Administrator"),
                        ],
                        default="PASSENGER",
                        max_length=30,
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=15)),
                (
                    "badge_number",
                    models.CharField(
                        blank=True,
                        help_text="Official ID for Railway staff",
                        max_length=50,
                    ),
                ),
                (
                    "assigned_station",
                    models.CharField(
                        blank=True,
                        help_text="Assigned Station Code/Name",
                        max_length=100,
                    ),
                ),
                (
                    "assigned_division",
                    models.CharField(
                        blank=True,
                        default="Northern Railway / Eastern Railway",
                        max_length=100,
                    ),
                ),
                ("emergency_contact", models.CharField(blank=True, max_length=15)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
