# Generated by Django 5.2.17 on 2026-09-06 20:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_jti",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("expires_at", models.DateTimeField()),
                ("is_revoked", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="assigned_division",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="assigned_station",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="avatar",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="emergency_contact",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="department_code",
            field=models.CharField(
                choices=[
                    ("ENG", "Engineering (Track & Civil P-Way)"),
                    ("TRD", "Traction Distribution (Electrical & OHE)"),
                    ("SNT", "Signal & Telecommunication"),
                    ("OPERATIONS", "Operating & Traffic Control (COA)"),
                    ("SAFETY", "Railway Safety Commissionerate"),
                ],
                db_index=True,
                default="ENG",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="division_code",
            field=models.CharField(
                default="DLI",
                help_text="Railway Division Code (e.g. DLI, HWH, KGP, ALD, MB)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="employee_id",
            field=models.CharField(
                db_index=True,
                default="EMP-001",
                help_text="Official Indian Railways Personnel / HRMS ID (e.g., NR-ENG-4921, IR-COA-1001)",
                max_length=30,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="failed_login_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_login_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="badge_number",
            field=models.CharField(
                blank=True,
                help_text="Official Station/Control Room Desk Tag",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "System Administrator"),
                    ("CHIEF_CONTROLLER", "Chief Controller (COA)"),
                    ("SECTION_CONTROLLER", "Section Controller"),
                    ("DEPT_ENGINEER", "Departmental Engineer (JE/SE)"),
                    ("SITE_SUPERVISOR", "Site Supervisor / Gang Leader"),
                    ("AUDITOR", "Operations & Safety Auditor"),
                ],
                db_index=True,
                default="DEPT_ENGINEER",
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["role", "department_code"], name="accounts_us_role_2cad8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["division_code"], name="accounts_us_divisio_006170_idx"
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "is_revoked"], name="accounts_us_user_id_bc9cc2_idx"
            ),
        ),
    ]
