# Generated by Django 5.2.17 on 2026-09-09 19:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usersession_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='employee_id',
            field=models.CharField(db_index=True, default=uuid.uuid4, help_text='Official Indian Railways Personnel / HRMS ID (e.g., NR-ENG-4921, IR-COA-1001)', max_length=36, unique=True),
        ),
    ]
