# Generated by Django 5.2.17 on 2026-09-06 20:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blocks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("ENG", "Engineering (Track & Civil P-Way)"),
                            ("TRD", "Traction Distribution (Electrical & OHE)"),
                            ("SNT", "Signal & Telecommunication"),
                            ("OPERATIONS", "Operating & Traffic Control (COA)"),
                            ("SAFETY", "Railway Safety Commissionerate"),
                        ],
                        db_index=True,
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "headquarters_division",
                    models.CharField(default="DLI", max_length=10),
                ),
                ("contact_email", models.EmailField(max_length=255)),
                ("escalation_phone", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Gang",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gang_number",
                    models.CharField(db_index=True, max_length=30, unique=True),
                ),
                (
                    "headquarters_station",
                    models.CharField(db_index=True, default="NDLS", max_length=10),
                ),
                ("crew_strength", models.PositiveIntegerField(default=12)),
                (
                    "assigned_section_start_km",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
                ),
                (
                    "assigned_section_end_km",
                    models.DecimalField(decimal_places=3, default=50.0, max_digits=8),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gangs",
                        to="departments.department",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervised_gangs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["department", "gang_number"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceEquipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "equipment_code",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("equipment_name", models.CharField(max_length=100)),
                (
                    "equipment_type",
                    models.CharField(
                        choices=[
                            (
                                "TRACK_TAMPER_CSM",
                                "Continuous Action Tamper (09-32 CSM)",
                            ),
                            (
                                "BALLAST_CLEANER_BCM",
                                "Ballast Cleaning Machine (RM-80 BCM)",
                            ),
                            (
                                "DYNAMIC_TRACK_STABILIZER",
                                "Dynamic Track Stabilizer (DGS 62N)",
                            ),
                            ("OHE_TOWER_WAGON", "8-Wheeler OHE Inspection Tower Car"),
                            (
                                "RAIL_GRINDING_TRAIN",
                                "Rail Grinding Machine (RGM 96 Stone)",
                            ),
                            ("USFD_TROLLEY", "Ultrasonic Flaw Detector Trolley"),
                        ],
                        db_index=True,
                        default="TRACK_TAMPER_CSM",
                        max_length=50,
                    ),
                ),
                ("home_depot", models.CharField(default="GZB", max_length=20)),
                (
                    "current_location_km",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
                ),
                (
                    "operational_status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("ASSIGNED", "Assigned to Block"),
                            ("MAINTENANCE_DUE", "Scheduled Maintenance Due"),
                            ("BREAKDOWN", "Breakdown / Out of Order"),
                        ],
                        db_index=True,
                        default="AVAILABLE",
                        max_length=30,
                    ),
                ),
                ("fitness_expiry_date", models.DateField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="equipment",
                        to="departments.department",
                    ),
                ),
            ],
            options={
                "ordering": ["department", "equipment_type", "equipment_code"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_number",
                    models.CharField(db_index=True, max_length=40, unique=True),
                ),
                ("planned_work_scope", models.TextField()),
                (
                    "target_metric_units",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="e.g. 1500 meters of track tamped",
                        max_digits=10,
                    ),
                ),
                (
                    "actual_metric_units",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Mobilization"),
                            ("MOBILIZING", "Crew & Machinery Mobilizing"),
                            ("ON_SITE", "On Site / Working"),
                            ("WORK_COMPLETED", "Work Completed"),
                            ("SAFETY_CLEARANCE_SIGNED", "Safety Clearance Signed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("ballast_profile_verified", models.BooleanField(default=False)),
                ("track_gauge_checked", models.BooleanField(default=False)),
                (
                    "safety_clearance_timestamp",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("safety_remarks", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_orders",
                        to="blocks.block",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="work_orders",
                        to="departments.department",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_orders",
                        to="departments.maintenanceequipment",
                    ),
                ),
                (
                    "gang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="work_orders",
                        to="departments.gang",
                    ),
                ),
                (
                    "safety_certified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certified_work_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="gang",
            index=models.Index(
                fields=["department", "headquarters_station"],
                name="idx_gang_dept_station",
            ),
        ),
        migrations.AddIndex(
            model_name="maintenanceequipment",
            index=models.Index(
                fields=["equipment_type", "operational_status"],
                name="idx_eq_type_status",
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(fields=["gang", "status"], name="idx_wo_gang_status"),
        ),
    ]
