# Generated by Django 5.2.17 on 2026-09-06 20:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Corridor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("zone", models.CharField(default="NR", max_length=10)),
                ("division", models.CharField(default="DLI", max_length=10)),
                ("source_station", models.CharField(default="NDLS", max_length=50)),
                ("destination_station", models.CharField(default="GZB", max_length=50)),
                (
                    "start_km",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
                ),
                (
                    "end_km",
                    models.DecimalField(decimal_places=3, default=28.5, max_digits=8),
                ),
                ("is_electrified", models.BooleanField(default=True)),
                ("max_permissible_speed_kmh", models.PositiveIntegerField(default=130)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "block_code",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "line_type",
                    models.CharField(
                        choices=[
                            ("UP", "Up Main Line (e.g. Towards NDLS)"),
                            ("DOWN", "Down Main Line (e.g. Towards GZB/CNB)"),
                            ("BIDIRECTIONAL", "Bi-directional Single Track"),
                            ("LOOP_1", "Loop Line 1 / Platform Line"),
                            ("LOOP_2", "Loop Line 2"),
                            ("YARD", "Marshalling Yard / Sidings"),
                        ],
                        default="DOWN",
                        max_length=20,
                    ),
                ),
                (
                    "department_code",
                    models.CharField(
                        choices=[
                            ("ENG", "Engineering (Track & Civil P-Way)"),
                            ("TRD", "Traction Distribution (Electrical & OHE)"),
                            ("SNT", "Signal & Telecommunication"),
                            ("OPERATIONS", "Operating & Traffic Control (COA)"),
                            ("SAFETY", "Railway Safety Commissionerate"),
                        ],
                        db_index=True,
                        default="ENG",
                        max_length=20,
                    ),
                ),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("TRACK_TAMPING", "Track Tamping (CSM Machine)"),
                            ("BALLAST_CLEANING", "Ballast Deep Screening (BCM)"),
                            ("RAIL_RENEWAL", "Through Rail Renewal (TRR)"),
                            ("OHE_INSPECTION", "25kV OHE Tower Wagon Inspection"),
                            (
                                "CATENARY_MAINTENANCE",
                                "Catenary & Contact Wire Adjustment",
                            ),
                            (
                                "SIGNAL_INTERLOCKING_TEST",
                                "Electronic Interlocking Point Overhaul",
                            ),
                            ("TURNOUT_OVERHAUL", "Turnout & Switch Crossing Renewal"),
                        ],
                        default="TRACK_TAMPING",
                        max_length=40,
                    ),
                ),
                (
                    "gang_id",
                    models.CharField(
                        blank=True,
                        help_text="Designated maintenance gang code",
                        max_length=50,
                    ),
                ),
                ("equipment_required", models.CharField(blank=True, max_length=150)),
                ("start_km", models.DecimalField(decimal_places=3, max_digits=8)),
                ("end_km", models.DecimalField(decimal_places=3, max_digits=8)),
                ("scheduled_start_time", models.DateTimeField(db_index=True)),
                ("scheduled_end_time", models.DateTimeField(db_index=True)),
                ("actual_start_time", models.DateTimeField(blank=True, null=True)),
                ("actual_end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "traction_power_cutoff_required",
                    models.BooleanField(
                        default=False, help_text="Requires 25kV OHE de-energization"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft Proposal"),
                            ("PENDING_APPROVAL", "Submitted to COA"),
                            ("COORDINATED", "Shadow-Block Coordinated"),
                            ("CONFLICT_DETECTED", "Spatial/Temporal Conflict"),
                            ("SANCTIONED", "Sanctioned by Chief Controller"),
                            ("ACTIVE", "Possession Live / Caution In Effect"),
                            ("COMPLETED", "Cleared & Safety Handback"),
                            ("CANCELLED", "Cancelled by Department"),
                            ("REJECTED", "Rejected by COA"),
                        ],
                        db_index=True,
                        default="PENDING_APPROVAL",
                        max_length=30,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("sanctioned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "caution_order_id",
                    models.CharField(
                        blank=True,
                        help_text="Official Caution Order ID (e.g. CO-2026-DLI-99)",
                        max_length=50,
                    ),
                ),
                (
                    "track_fit_certified",
                    models.BooleanField(
                        default=False,
                        help_text="Final physical safety sign-off before handback",
                    ),
                ),
                ("is_shadow", models.BooleanField(db_index=True, default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("work_description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shadow_blocks",
                        to="blocks.block",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_blocks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sanctioned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sanctioned_blocks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "corridor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="blocks",
                        to="blocks.corridor",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_start_time"],
            },
        ),
        migrations.CreateModel(
            name="BlockConflict",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "conflict_type",
                    models.CharField(
                        choices=[
                            ("TRAIN_PATH_COLLISION", "Train Timetable Collision"),
                            (
                                "PARALLEL_BLOCK_COLLISION",
                                "Parallel Block Possession Overlap",
                            ),
                            (
                                "OHE_POWER_CONCURRENT_LOCK",
                                "Conflicting OHE Power Cut Zone",
                            ),
                            (
                                "SAFETY_MARGIN_VIOLATION",
                                "Headway / Safety Buffer Violation",
                            ),
                        ],
                        default="PARALLEL_BLOCK_COLLISION",
                        max_length=40,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            (
                                "CRITICAL",
                                "Critical Hazard / Prestige Train Interruption",
                            ),
                            ("HIGH", "High Priority Overlap"),
                            ("MEDIUM", "Medium Delay Potential"),
                            ("LOW", "Low Operational Margin"),
                        ],
                        db_index=True,
                        default="HIGH",
                        max_length=20,
                    ),
                ),
                (
                    "conflicting_entity_id",
                    models.CharField(db_index=True, max_length=64),
                ),
                (
                    "conflicting_entity_label",
                    models.CharField(blank=True, max_length=150),
                ),
                (
                    "overlap_start_km",
                    models.DecimalField(decimal_places=3, max_digits=8),
                ),
                ("overlap_end_km", models.DecimalField(decimal_places=3, max_digits=8)),
                ("conflict_start_time", models.DateTimeField()),
                ("conflict_end_time", models.DateTimeField()),
                (
                    "resolution_status",
                    models.CharField(
                        choices=[
                            ("UNRESOLVED", "Unresolved Conflict"),
                            ("AUTO_RESOLVED", "Automated Resolution Proposed"),
                            ("SHADOW_MERGED", "Merged as Shadow Co-Possession"),
                            ("MANUALLY_OVERRIDDEN", "Controller Authorized Override"),
                            ("DISMISSED", "Dismissed / Inapplicable"),
                        ],
                        db_index=True,
                        default="UNRESOLVED",
                        max_length=30,
                    ),
                ),
                ("resolution_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts",
                        to="blocks.block",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="block",
            index=models.Index(
                fields=["corridor", "scheduled_start_time", "scheduled_end_time"],
                name="blocks_bloc_corrido_a4ccc2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="block",
            index=models.Index(
                fields=["status", "department_code"],
                name="blocks_bloc_status_2092a8_idx",
            ),
        ),
    ]
