# Generated by Django 5.2.17 on 2026-09-19 09:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('from_station', models.CharField(max_length=50)),
                ('to_station', models.CharField(max_length=50)),
                ('start_km', models.DecimalField(decimal_places=3, max_digits=8)),
                ('end_km', models.DecimalField(decimal_places=3, max_digits=8)),
                ('line_type', models.CharField(choices=[('UP', 'Up Main Line (e.g. Towards NDLS)'), ('DOWN', 'Down Main Line (e.g. Towards GZB/CNB)'), ('BIDIRECTIONAL', 'Bi-directional Single Track'), ('LOOP_1', 'Loop Line 1 / Platform Line'), ('LOOP_2', 'Loop Line 2'), ('YARD', 'Marshalling Yard / Sidings')], default='DOWN', max_length=20)),
                ('is_electrified', models.BooleanField(default=True)),
                ('max_speed_kmh', models.PositiveIntegerField(default=130)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corridor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='blocks.corridor')),
            ],
            options={
                'ordering': ['start_km'],
            },
        ),
    ]
