# Generated by Django 5.2.17 on 2026-09-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blocks", "0002_blocksection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft Proposal"),
                    ("PENDING_APPROVAL", "Submitted to COA"),
                    ("COORDINATED", "Shadow-Block Coordinated"),
                    ("CONFLICT_DETECTED", "Spatial/Temporal Conflict"),
                    ("SANCTIONED", "Sanctioned by Chief Controller"),
                    ("ACTIVE", "Possession Live / Caution In Effect"),
                    ("COMPLETED", "Cleared & Safety Handback"),
                    ("CANCELLED", "Cancelled by Department"),
                    ("REJECTED", "Rejected by COA"),
                    ("SUPERSEDED_BY_BUNDLE", "Superseded by Combined Block"),
                ],
                db_index=True,
                default="PENDING_APPROVAL",
                max_length=30,
            ),
        ),
    ]
