# Generated by Django 5.2.17 on 2026-09-02 18:47

import apps.maintenance.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DefectReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_id",
                    models.CharField(
                        default=apps.maintenance.models.generate_defect_id,
                        editable=False,
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "defect_type",
                    models.CharField(
                        choices=[
                            ("TRACK_CRACK", "Track Rail Fracture / Crack"),
                            ("JOINT_GAP", "Fishplate / Rail Joint Gap"),
                            ("OHE_SAG", "Overhead Wire (OHE) Sag / Tension Drop"),
                            ("WHEEL_HOT_AXLE", "Wheel Flat / Hot Axle Box Temperature"),
                            ("PANTOGRAPH_FAULT", "Pantograph Arc / Entanglement"),
                            (
                                "SIGNAL_INTERLOCK",
                                "Track Circuit / Signal Interlock Glitch",
                            ),
                            (
                                "COACH_MECHANICAL",
                                "Coach Automatic Door / Brake Pipe Failure",
                            ),
                        ],
                        default="TRACK_CRACK",
                        max_length=40,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "🔴 Critical (Immediate Train Halt Required)"),
                            ("MAJOR", "🟠 Major (Speed Restriction 30 km/h)"),
                            ("MINOR", "🟡 Minor (Schedule Routine Maintenance)"),
                        ],
                        default="MAJOR",
                        max_length=20,
                    ),
                ),
                (
                    "section_name",
                    models.CharField(
                        help_text="e.g. Kanpur - Prayagraj Section", max_length=150
                    ),
                ),
                (
                    "track_km_marker",
                    models.CharField(
                        help_text="e.g. KM 442/18 - 442/20", max_length=50
                    ),
                ),
                ("latitude", models.FloatField(default=28.6139)),
                ("longitude", models.FloatField(default=77.209)),
                (
                    "train_number",
                    models.CharField(
                        blank=True,
                        help_text="If detected on coach or rolling stock",
                        max_length=20,
                    ),
                ),
                ("coach_number", models.CharField(blank=True, max_length=20)),
                ("description", models.TextField()),
                (
                    "ai_confidence_score",
                    models.FloatField(
                        default=92.5, help_text="AI Model Confidence % (e.g. 94.2%)"
                    ),
                ),
                (
                    "detected_by",
                    models.CharField(
                        default="RailVision AI Camera / Sensor Array", max_length=100
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="maintenance_defects/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DETECTED", "Detected / AI Alerted"),
                            ("ASSIGNED", "Assigned to Crew"),
                            ("IN_REPAIR", "Maintenance In Progress"),
                            ("RESOLVED", "Repaired & Cleared"),
                            ("VERIFIED", "Safety Certified & Closed"),
                        ],
                        default="DETECTED",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        default=apps.maintenance.models.generate_work_order_id,
                        editable=False,
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "assigned_crew",
                    models.CharField(
                        default="Track Inspection Gang #4 - Northern Railway",
                        max_length=150,
                    ),
                ),
                ("target_completion_time", models.DateTimeField(blank=True, null=True)),
                ("repair_summary", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Assigned", "Assigned"),
                            ("Dispatched", "Team Dispatched on Site"),
                            ("Work_Completed", "Work Completed"),
                            ("Safety_Certified", "Safety Certified"),
                        ],
                        default="Assigned",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_engineer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_work_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "defect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_orders",
                        to="maintenance.defectreport",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
