# Generated by Django 5.2.17 on 2026-09-07 16:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blocks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "asset_tag",
                    models.CharField(db_index=True, max_length=60, unique=True),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "asset_category",
                    models.CharField(
                        choices=[
                            (
                                "PERMANENT_WAY",
                                "Permanent Way (Rails, Sleepers, Ballast)",
                            ),
                            ("OHE_TRACTION", "25kV Traction Overhead Equipment"),
                            ("SIGNAL_INTERLOCKING", "Signaling & Interlocking"),
                            ("TELECOM", "Telecommunications & Axle Counters"),
                            ("BRIDGES_STRUCTURES", "Bridges, Culverts & Structures"),
                        ],
                        db_index=True,
                        default="PERMANENT_WAY",
                        max_length=40,
                    ),
                ),
                (
                    "sub_type",
                    models.CharField(
                        help_text="e.g. 60KG_UIC_RAIL, POINT_MACHINE_143, OHE_CANTILEVER",
                        max_length=80,
                    ),
                ),
                (
                    "location_km",
                    models.DecimalField(db_index=True, decimal_places=3, max_digits=8),
                ),
                (
                    "line_type",
                    models.CharField(
                        choices=[
                            ("UP", "Up Main Line (e.g. Towards NDLS)"),
                            ("DOWN", "Down Main Line (e.g. Towards GZB/CNB)"),
                            ("BIDIRECTIONAL", "Bi-directional Single Track"),
                            ("LOOP_1", "Loop Line 1 / Platform Line"),
                            ("LOOP_2", "Loop Line 2"),
                            ("YARD", "Marshalling Yard / Sidings"),
                        ],
                        default="DOWN",
                        max_length=20,
                    ),
                ),
                ("installation_date", models.DateField(blank=True, null=True)),
                (
                    "current_health_score",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        default=100.0,
                        help_text="100.0 = Brand New, < 40.0 = Critical Maintenance Required",
                        max_digits=5,
                    ),
                ),
                (
                    "tqi_index",
                    models.DecimalField(
                        decimal_places=2,
                        default=24.5,
                        help_text="Track Quality Index (RDSO TRC standard)",
                        max_digits=5,
                    ),
                ),
                ("last_inspected_at", models.DateTimeField(blank=True, null=True)),
                ("is_operational", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "corridor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="track_assets",
                        to="blocks.corridor",
                    ),
                ),
            ],
            options={
                "db_table": "track_assets",
                "ordering": ["corridor", "location_km"],
            },
        ),
        migrations.CreateModel(
            name="AssetDefectLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "defect_code",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "defect_type",
                    models.CharField(
                        choices=[
                            (
                                "INTERNAL_RAIL_FRACTURE",
                                "Internal Rail Fracture / Transverse Fissure",
                            ),
                            ("WHEEL_BURN", "Wheel Burn / Scabbing"),
                            (
                                "OHE_SAG_EXCESSIVE",
                                "Excessive Catenary / Contact Wire Sag",
                            ),
                            (
                                "POINT_SLACK_TIMEOUT",
                                "Points Machine Slack / Detection Timeout",
                            ),
                            (
                                "INSULATION_BREAKDOWN",
                                "Track Circuit Insulation Breakdown",
                            ),
                            ("WELD_COLLAPSE", "Thermit Weld Joint Failure"),
                        ],
                        default="INTERNAL_RAIL_FRACTURE",
                        max_length=40,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            (
                                "CRITICAL_IMMEDIATE_STOP",
                                "Critical Flaw - Immediate Train Stop (IMR)",
                            ),
                            (
                                "IMPAIRMENT_SPEED_RESTRICTION",
                                "Safety Impairment - Speed Restriction (OBS)",
                            ),
                            ("MONITORING_REQUIRED", "Routine Monitoring Required"),
                        ],
                        db_index=True,
                        default="IMPAIRMENT_SPEED_RESTRICTION",
                        max_length=40,
                    ),
                ),
                (
                    "detected_by_source",
                    models.CharField(
                        default="USFD_ULTRASONIC",
                        help_text="e.g. USFD_CAR_04, MANUAL_TROLLEY_INSPECTION",
                        max_length=60,
                    ),
                ),
                (
                    "flaw_depth_mm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="USFD flaw depth in mm",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "recommended_speed_restriction_kmh",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Temporary Caution Order speed restriction (km/h)",
                        null=True,
                    ),
                ),
                (
                    "block_recommended",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True if defect warrants immediate or scheduled maintenance block",
                    ),
                ),
                ("is_rectified", models.BooleanField(db_index=True, default=False)),
                ("description", models.TextField(blank=True)),
                (
                    "emergency_block_id",
                    models.CharField(
                        blank=True,
                        help_text="Linked automated emergency block UUID",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("rectified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defects",
                        to="assets.trackasset",
                    ),
                ),
            ],
            options={
                "db_table": "asset_defect_logs",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.AddIndex(
            model_name="trackasset",
            index=models.Index(
                fields=["corridor", "location_km"],
                name="track_asset_corrido_d781fc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trackasset",
            index=models.Index(
                fields=["current_health_score"], name="track_asset_current_8e09c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trackasset",
            index=models.Index(
                fields=["asset_category", "is_operational"],
                name="track_asset_asset_c_989662_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assetdefectlog",
            index=models.Index(
                fields=["asset", "is_rectified"], name="asset_defec_asset_i_c35bd2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assetdefectlog",
            index=models.Index(
                fields=["severity", "is_rectified"],
                name="asset_defec_severit_cdd64c_idx",
            ),
        ),
    ]
