# Generated by Django 5.2.17 on 2026-09-20 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetdefectlog',
            name='cof_score',
            field=models.PositiveSmallIntegerField(default=3, help_text='Consequence of Failure (1-5, Feature #92)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='assetdefectlog',
            name='lof_score',
            field=models.PositiveSmallIntegerField(default=3, help_text='Likelihood of Failure (1-5, Feature #92)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='assetdefectlog',
            name='overdue_days',
            field=models.PositiveIntegerField(default=0, help_text='Days defect has been active/overdue since initial detection (Feature #93)'),
        ),
    ]
