import json
import urllib.request
import urllib.error
import subprocess
import sys

FRONTEND_URL = "http://localhost:3000"
BACKEND_URL = "http://127.0.0.1:8000"

def log_step(title):
    print("\n" + "=" * 80)
    print(f"STEP: {title}")
    print("=" * 80)

def http_request(url, method="GET", headers=None, data=None):
    if headers is None:
        headers = {}
    body_bytes = None
    if data is not None:
        body_bytes = json.dumps(data).encode("utf-8")
        headers["Content-Type"] = "application/json"
    req = urllib.request.Request(url, data=body_bytes, headers=headers, method=method)
    try:
        resp = urllib.request.urlopen(req, timeout=10)
        resp_body = resp.read().decode("utf-8")
        try:
            return resp.status, json.loads(resp_body)
        except Exception:
            return resp.status, resp_body
    except urllib.error.HTTPError as e:
        resp_body = e.read().decode("utf-8")
        try:
            return e.code, json.loads(resp_body)
        except Exception:
            return e.code, resp_body

print("=" * 80)
print("RUNNING E2E TEST SUITE: TSK-P2-02-TEST")
print("SUBMITTING BLOCK VIA FRONTEND & VERIFYING BACKEND DATABASE PERSISTENCE")
print("=" * 80)

# ----------------------------------------------------------------------
# 1. Authenticate as P-Way Track Engineer via Frontend Proxy
# ----------------------------------------------------------------------
log_step("1. Authenticating Track Engineer (eng_track_pway) via Frontend Proxy")
status, login_res = http_request(
    f"{FRONTEND_URL}/api/v1/auth/login/",
    method="POST",
    data={"username": "eng_track_pway", "password": "railway@123"}
)
print(f"Frontend Login Response: HTTP {status}")
assert status == 200, f"Login failed: {login_res}"
assert login_res.get("success") is True
token = login_res["data"]["access_token"]
user = login_res["data"]["user"]
user_name = user.get('full_name') or f"{user.get('first_name', '')} {user.get('last_name', '')}".strip() or user.get('username')
print(f"[OK] Engineer authenticated: {user_name} ({user.get('role')})")
print(f"  * Department: {user.get('department_code')}")

# ----------------------------------------------------------------------
# 2. Submit Block Proposal via Frontend API Route (POST /api/v1/blocks/)
# ----------------------------------------------------------------------
log_step("2. Submitting Block Proposal Wizard Payload via Frontend Reverse Proxy")
# Exact payload generated by BlockRequestForm.tsx
wizard_payload = {
    "corridor": "NDLS-CNB-MAIN",
    "department": "ENG",
    "line_type": "DOWN",
    "work_type": "Track Tamping (CSM)",
    "start_km": 18.200,
    "end_km": 22.500,
    "scheduled_start_time": "2026-09-20T03:00:00+05:30",
    "scheduled_end_time": "2026-09-20T06:00:00+05:30",
    "gang_id": "GANG-ENG-01",
    "equipment_required": "CSM-09-32",
    "traction_power_cutoff_required": False,
    "work_description": "Mechanized tamping & track geometrical realignment by Gang 01"
}

status_post, post_res = http_request(
    f"{FRONTEND_URL}/api/v1/blocks/",
    method="POST",
    headers={"Authorization": f"Bearer {token}"},
    data=wizard_payload
)
print(f"Frontend Block Submission Response: HTTP {status_post}")
assert status_post == 201, f"Expected 201 Created, got {status_post}: {post_res}"
assert post_res.get("success") is True, "Expected success: true"

created_block = post_res["data"]
block_id = created_block["id"]
block_code = created_block["block_code"]
print(f"[OK] Block proposal successfully accepted via frontend proxy:")
print(f"  * Block Code:      {block_code}")
print(f"  * UUID:            {block_id}")
print(f"  * Status:          {created_block['status']} ({created_block['status_display']})")
print(f"  * Span:            KM {created_block['start_km']} to KM {created_block['end_km']} ({created_block['span_km']} km)")
print(f"  * Corridor:        {created_block['corridor_code']}")
print(f"  * Conflicts Found: {created_block.get('sweep_report', {}).get('total_conflicts', 0)}")

# ----------------------------------------------------------------------
# 3. Verify Direct Backend PostgreSQL Database Persistence
# ----------------------------------------------------------------------
log_step("3. Verifying Direct PostgreSQL Database State on Backend (Port 8000)")
status_be, be_res = http_request(
    f"{BACKEND_URL}/api/v1/blocks/{block_id}/",
    headers={"Authorization": f"Bearer {token}"}
)
print(f"Direct Backend Query: HTTP {status_be}")
assert status_be == 200, f"Expected 200, got {status_be}: {be_res}"
assert be_res.get("success") is True

db_block = be_res["data"]
assert db_block["id"] == block_id, "DB ID must match"
assert db_block["block_code"] == block_code, "DB block_code must match"
assert float(db_block["start_km"]) == 18.2, f"Expected start_km 18.2, got {db_block['start_km']}"
assert float(db_block["end_km"]) == 22.5, f"Expected end_km 22.5, got {db_block['end_km']}"
assert db_block["department_code"] == "ENG", "Department code must be ENG"
assert db_block["gang_id"] == "GANG-ENG-01", "Gang ID must match"
assert db_block["equipment_required"] == "CSM-09-32", "Equipment must match"
assert db_block["status"] in ["PENDING_APPROVAL", "COORDINATED", "CONFLICT_DETECTED"]
print("[OK] Real database persistence confirmed in PostgreSQL with 100% field integrity")

# ----------------------------------------------------------------------
# 4. Verify Presence in Departmental Block List (GET /api/v1/blocks/?department=ENG)
# ----------------------------------------------------------------------
log_step("4. Verifying Presence in Frontend Departmental Block List")
status_list, list_res = http_request(
    f"{FRONTEND_URL}/api/v1/blocks/?department=ENG",
    headers={"Authorization": f"Bearer {token}"}
)
assert status_list == 200, f"Expected 200, got {status_list}"
assert list_res.get("success") is True

blocks_list = list_res["data"]
matching = [b for b in blocks_list if b["id"] == block_id or b["block_code"] == block_code]
assert len(matching) > 0, f"Newly created block {block_code} must appear in departmental block list"
print(f"[OK] Block {block_code} successfully retrieved in frontend departmental block list (Total blocks: {len(blocks_list)})")

# ----------------------------------------------------------------------
# 5. Verify Frontend-to-Backend Coherence Rejection Handling (Rule 1 & Rule 2)
# ----------------------------------------------------------------------
log_step("5. Testing End-to-End Coherence Violation Propagation through Frontend Proxy")

# 5a. Out-of-bounds KM (>440.2 km)
invalid_geo = wizard_payload.copy()
invalid_geo["start_km"] = 445.0
invalid_geo["end_km"] = 455.0
status_geo_err, res_geo_err = http_request(
    f"{FRONTEND_URL}/api/v1/blocks/",
    method="POST",
    headers={"Authorization": f"Bearer {token}"},
    data=invalid_geo
)
print(f"Rule 1 Out-of-Bounds Submission: HTTP {status_geo_err}")
assert status_geo_err == 400, f"Expected 400, got {status_geo_err}"
assert res_geo_err.get("success") is False
print(f"[OK] Rule 1 violation error details propagated: {res_geo_err.get('error', {}).get('details')}")

# 5b. Excessive duration (>8 hours: 03:00 to 12:00 = 9h)
invalid_dur = wizard_payload.copy()
invalid_dur["scheduled_start_time"] = "2026-09-20T03:00:00+05:30"
invalid_dur["scheduled_end_time"] = "2026-09-20T12:00:00+05:30"
status_dur_err, res_dur_err = http_request(
    f"{FRONTEND_URL}/api/v1/blocks/",
    method="POST",
    headers={"Authorization": f"Bearer {token}"},
    data=invalid_dur
)
print(f"Rule 2 Excessive Duration Submission: HTTP {status_dur_err}")
assert status_dur_err == 400, f"Expected 400, got {status_dur_err}"
assert res_dur_err.get("success") is False
print(f"[OK] Rule 2 violation error details propagated: {res_dur_err.get('error', {}).get('details')}")

print("\n" + "=" * 80)
print("ALL TSK-P2-02-TEST VERIFICATION CHECKS PASSED (100%)")
print("=" * 80)
