# Generated by Django 5.2.17 on 2026-09-06 21:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OntologyGraph",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version_tag",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("owl_file_hash", models.CharField(max_length=64)),
                ("total_classes", models.PositiveIntegerField(default=0)),
                ("total_properties", models.PositiveIntegerField(default=0)),
                ("total_individuals", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("compiled_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ontology_graphs",
                "ordering": ["-compiled_at"],
            },
        ),
        migrations.CreateModel(
            name="SemanticViolation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("block_id", models.CharField(db_index=True, max_length=64)),
                ("rule_identifier", models.CharField(db_index=True, max_length=80)),
                (
                    "violation_type",
                    models.CharField(
                        choices=[
                            ("STRANDED_ELECTRIC_TRAIN", "Stranded Electric Train"),
                            ("CROSSOVER_POINTS_DEADLOCK", "Crossover Points Deadlock"),
                            ("SIGNAL_OVERLAP_INVASION", "Signal Overlap Invasion"),
                            (
                                "FEEDER_ISOLATION_CONCURRENCY",
                                "Feeder Isolation Concurrency",
                            ),
                        ],
                        default="STRANDED_ELECTRIC_TRAIN",
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("CRITICAL_SAFETY", "Critical Safety"),
                            ("OPERATIONAL_IMPEDIMENT", "Operational Impediment"),
                            ("ADVISORY", "Advisory"),
                        ],
                        default="CRITICAL_SAFETY",
                        max_length=30,
                    ),
                ),
                (
                    "explanation_narrative",
                    models.TextField(help_text="DL explanation narrative proof"),
                ),
                ("involved_owl_individuals", models.JSONField(default=list)),
                ("resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "graph",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violations",
                        to="ontology.ontologygraph",
                    ),
                ),
            ],
            options={
                "db_table": "semantic_violations",
                "ordering": ["-created_at"],
            },
        ),
    ]
