# Generated by Django 5.2.17 on 2026-09-07 16:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlockEfficiencyRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("block_id", models.CharField(db_index=True, max_length=64)),
                (
                    "corridor_code",
                    models.CharField(db_index=True, default="NDLS-CNB", max_length=50),
                ),
                ("planned_hours", models.DecimalField(decimal_places=2, max_digits=5)),
                ("actual_hours", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "burst_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Duration exceeded beyond sanctioned window",
                        max_digits=5,
                    ),
                ),
                (
                    "gang_utilization_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=100.0,
                        help_text="Productivity output per worker hour (%)",
                        max_digits=5,
                    ),
                ),
                ("trains_delayed_count", models.PositiveIntegerField(default=0)),
                ("total_delay_minutes", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "block_efficiency_records",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["block_id"], name="block_effic_block_i_9d8840_idx"
                    ),
                    models.Index(
                        fields=["corridor_code", "created_at"],
                        name="block_effic_corrido_3fb621_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CorridorDailyKPI",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("metric_date", models.DateField(db_index=True)),
                (
                    "division_code",
                    models.CharField(db_index=True, default="DLI", max_length=10),
                ),
                ("corridor_code", models.CharField(db_index=True, max_length=50)),
                ("total_blocks_requested", models.PositiveIntegerField(default=0)),
                ("total_blocks_sanctioned", models.PositiveIntegerField(default=0)),
                ("total_blocks_executed", models.PositiveIntegerField(default=0)),
                (
                    "total_sanctioned_duration_minutes",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "total_actual_duration_minutes",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "total_possession_hours",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
                ),
                (
                    "co_possession_blocks_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Blocks where 2 or more departments worked simultaneously",
                    ),
                ),
                (
                    "total_train_delay_minutes_incurred",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "corridor_punctuality_percentage",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
                ),
                (
                    "conflict_mitigation_rate_pct",
                    models.DecimalField(decimal_places=2, default=88.0, max_digits=5),
                ),
                ("shadow_blocks_count", models.PositiveIntegerField(default=0)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "corridor_daily_kpis",
                "ordering": ["-metric_date", "corridor_code"],
                "indexes": [
                    models.Index(
                        fields=["metric_date", "division_code", "corridor_code"],
                        name="corridor_da_metric__8fee08_idx",
                    ),
                    models.Index(
                        fields=["corridor_code", "metric_date"],
                        name="corridor_da_corrido_340d6a_idx",
                    ),
                ],
                "unique_together": {("metric_date", "division_code", "corridor_code")},
            },
        ),
    ]
