# Generated by Django 5.2.17 on 2026-09-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corridordailykpi',
            name='average_tqi_score',
            field=models.DecimalField(decimal_places=2, default=24.5, help_text='Corridor average Track Quality Index (RDSO TRC standard)', max_digits=5),
        ),
        migrations.AddField(
            model_name='corridordailykpi',
            name='cancelled_blocks_count',
            field=models.PositiveIntegerField(default=0, help_text='Blocks rejected or cancelled'),
        ),
        migrations.AddField(
            model_name='corridordailykpi',
            name='shadow_bundling_ratio_pct',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Shadow block bundling ratio (% of total blocks bundled)', max_digits=5),
        ),
        migrations.AddField(
            model_name='corridordailykpi',
            name='tqi_status',
            field=models.CharField(default='GOOD', help_text='TQI classification: EXCELLENT (<20), GOOD (20-30), FAIR (30-45), URGENT (>45)', max_length=25),
        ),
    ]
