# Generated by Django 5.2.17 on 2026-09-07 16:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recipient_role",
                    models.CharField(
                        db_index=True,
                        default="ALL",
                        help_text="Target role (e.g. CHIEF_CONTROLLER, DEPT_ENGINEER, ALL)",
                        max_length=40,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("CRITICAL_EMERGENCY", "Critical Emergency"),
                            ("HIGH_OPERATIONAL", "High Operational Priority"),
                            ("ROUTINE_INFO", "Routine Information"),
                        ],
                        db_index=True,
                        default="ROUTINE_INFO",
                        max_length=30,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BLOCK_SANCTIONED", "Block Sanctioned"),
                            ("BLOCK_BURST_WARNING", "Block Burst Warning"),
                            ("SAFETY_CONFLICT_ALARM", "Safety Conflict Alarm"),
                            ("WORK_ORDER_ASSIGNED", "Work Order Assigned"),
                            ("TRAIN_DELAY_ALERT", "Train Delay Alert"),
                            ("CRITICAL_DEFECT_DETECTED", "Critical Defect Detected"),
                            ("GENERAL_INFO", "General Information"),
                        ],
                        default="GENERAL_INFO",
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("message_body", models.TextField()),
                (
                    "target_entity_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g. BLOCK, TRAIN, ASSET, WORK_ORDER",
                        max_length=50,
                    ),
                ),
                ("target_entity_id", models.CharField(blank=True, max_length=64)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Target user, or null for role/system broadcast",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationDeliveryLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("WEBSOCKET_INAPP", "WebSocket In-App"),
                            ("SMS_GATEWAY", "CDAC Cellular SMS"),
                            ("EMAIL", "Official Railway Email"),
                        ],
                        default="WEBSOCKET_INAPP",
                        max_length=30,
                    ),
                ),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued for Dispatch"),
                            ("DISPATCHED", "Dispatched to Carrier"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                            ("DEAD_LETTER", "Dead Letter Archived"),
                        ],
                        db_index=True,
                        default="QUEUED",
                        max_length=30,
                    ),
                ),
                (
                    "external_reference_id",
                    models.CharField(
                        blank=True,
                        help_text="Telco/CDAC SMS gateway message ID",
                        max_length=100,
                    ),
                ),
                ("retry_attempts", models.PositiveIntegerField(default=0)),
                ("error_details", models.TextField(blank=True)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_logs",
                        to="notifications.notification",
                    ),
                ),
            ],
            options={
                "db_table": "notification_delivery_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient_user", "is_read"],
                name="notificatio_recipie_ab3f2f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient_role", "priority"],
                name="notificatio_recipie_490866_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["priority", "created_at"], name="notificatio_priorit_22e6c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdeliverylog",
            index=models.Index(
                fields=["notification", "channel"],
                name="notificatio_notific_65810f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdeliverylog",
            index=models.Index(
                fields=["delivery_status", "retry_attempts"],
                name="notificatio_deliver_a59f1a_idx",
            ),
        ),
    ]
