# Generated by Django 5.2.17 on 2026-09-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="priority",
            field=models.CharField(
                choices=[
                    ("CRITICAL_EMERGENCY", "Critical Emergency"),
                    ("CRITICAL_ALARM", "Critical Alarm"),
                    ("HIGH_OPERATIONAL", "High Operational Priority"),
                    ("URGENT_ACTION", "Urgent Action"),
                    ("ROUTINE_INFO", "Routine Information"),
                ],
                db_index=True,
                default="ROUTINE_INFO",
                max_length=30,
            ),
        ),
    ]
